version: 2

project_name: equationlabs-php-cli

before:
  hooks:
    - go mod tidy
    - go test -cover ./...

builds:
  - binary: equationlabs-php-cli
    id: equationlabs-php-cli-build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X 'main.buildDate={{ .Date }}' -X 'main.buildVersion={{ .Version }}'
    flags:
      - -trimpath

universal_binaries:
  - id: "{{ .ProjectName }}"
    ids:
      - equationlabs-php-cli-build
    replace: true

archives:
  - formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE

source:
  enabled: true

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}--checksums.txt"

signs:
  - artifacts: all
    cmd: cosign
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    env:
      - "COSIGN_EXPERIMENTAL=1"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge branch
      - Merge pull request

brews:
  - homepage: https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator
    description: EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)
    repository:
      owner: equationlabs
      name: eqlabs-tools-php-cli-homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Raul Castellanos
      email: raul.c@equationlabs.io
    commit_msg_template: "Brew Formula update for {{ .ProjectName }} version {{ .Version }}"
    directory: Formula
    caveats: |-
      To install shell completions, type the following command for instructions:
        equationlabs-php-cli completion --help
    license: MIT
    test: |
      system "#{bin}/equationlabs-php-cli --version"
    dependencies:
      - name: composer
    install: |-
      bin.install "equationlabs-php-cli"

dockers:
  - image_templates: [ "ghcr.io/equationlabs/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates: [ "ghcr.io/equationlabs/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: ghcr.io/equationlabs/{{ .ProjectName }}:{{ .Version }}
    image_templates: &docker_images
      - ghcr.io/equationlabs/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/equationlabs/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/equationlabs/{{ .ProjectName }}:v{{ .Major }}
    image_templates: *docker_images
  - name_template: ghcr.io/equationlabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates: *docker_images
  - name_template: ghcr.io/equationlabs/{{ .ProjectName }}:latest
    image_templates: *docker_images


release:
  prerelease: auto
  footer: >-

    ---

    Released with ❤️ by [EquationLabs I/O](https://www.equationlabs.io) and the help of [GoReleaser](https://github.com/goreleaser/goreleaser).
