services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app