name: Release Pipeline

on:
    push:
        tags:
            - v*

permissions:
    contents: write
    id-token: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - '1.24'

        steps:
            - name: Checkout
              id: checkout-source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up QEMU
              id: qemu-for-multiarch-docker-images
              uses: docker/setup-qemu-action@v3

            - name: Login into Github Docker Registry
              id: docker-login
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
              if: startsWith(github.ref, 'refs/tags/v')

            - name: Cosign installer
              id: cosign-installer
              uses: sigstore/cosign-installer@v3

            - name: Generate Releease
              id: go-releaser-production
              uses: goreleaser/goreleaser-action@v6
              with:
                  version: ${{ env.GITHUB_REF_NAME }}
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
