name: Release Pipeline

on:
    push:
        tags:
            - v*

permissions:
    contents: write
    id-token: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - '1.24'

        steps:
            - name: Checkout
              id: checkout-source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Cosign installer
              id: cosign-installer
              uses: sigstore/cosign-installer@v3


            - name: Generate Releease
              id: go-releaser-production
              uses: goreleaser/goreleaser-action@v6
              with:
                  version: ${{ env.GITHUB_REF_NAME }}
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}